services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: nest-postgres
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  #postgres:
  #  image: postgres:16.3-alpine
  #  container_name: postgres
  #  restart: always
  #  ports:
  #    - ${DB_PORT}:${DB_PORT}
  #  environment:
  #    POSTGRES_USER: ${DB_USERNAME}
  #    POSTGRES_PASSWORD: ${DB_PASSWORD}
  #    POSTGRES_DB: ${DB_NAME}
  #  env_file:
  #    - .env
  #  volumes:
  #    - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db