name: nestjs-prisma
services:
  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the 
  # address of this container.
  postgres:
    container_name: nest-postgres
    image: janlibal/pg-multipledb # postgres:16.3-alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DB_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${MULTIPLE_DATABASES}
    volumes:
      - postgres:/var/lib/postgresql/data
  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    container_name: nest-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres
    
volumes:
  postgres:
    name: boilerplate-db
  redis:
    driver: local
      